<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221026012711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activation (id INT AUTO_INCREMENT NOT NULL, card_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', amount DOUBLE PRECISION DEFAULT NULL, monthto INT NOT NULL, INDEX IDX_1C6860774ACC9A20 (card_id), INDEX IDX_1C686077B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bouquet (id INT AUTO_INCREMENT NOT NULL, price DOUBLE PRECISION DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, numero INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE card (id INT AUTO_INCREMENT NOT NULL, numerocard VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, bouquets LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE card_customer (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, card_id INT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, periodto DATETIME DEFAULT NULL, INDEX IDX_3808408A9395C3F3 (customer_id), INDEX IDX_3808408A4ACC9A20 (card_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, compte_id INT DEFAULT NULL, datecreation DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_81398E09F2C56620 (compte_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE souscription (id INT AUTO_INCREMENT NOT NULL, bouquet_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, created DATETIME DEFAULT NULL, expired_at DATETIME DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, INDEX IDX_2AED620D6C8DF983 (bouquet_id), INDEX IDX_2AED620D9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(250) NOT NULL, phone VARCHAR(250) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, isactivate TINYINT(1) DEFAULT NULL, facebook_id VARCHAR(250) DEFAULT NULL, google_id VARCHAR(250) DEFAULT NULL, avatar VARCHAR(250) DEFAULT NULL, userid INT DEFAULT NULL, bouquets JSON DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE activation ADD CONSTRAINT FK_1C6860774ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id)');
        $this->addSql('ALTER TABLE activation ADD CONSTRAINT FK_1C686077B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE card_customer ADD CONSTRAINT FK_3808408A9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE card_customer ADD CONSTRAINT FK_3808408A4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09F2C56620 FOREIGN KEY (compte_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE souscription ADD CONSTRAINT FK_2AED620D6C8DF983 FOREIGN KEY (bouquet_id) REFERENCES bouquet (id)');
        $this->addSql('ALTER TABLE souscription ADD CONSTRAINT FK_2AED620D9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('DROP TABLE ACInfo');
        $this->addSql('DROP TABLE Accredit');
        $this->addSql('DROP TABLE AllCardStatus');
        $this->addSql('DROP TABLE AllSendCard');
        $this->addSql('DROP TABLE AllTableCount');
        $this->addSql('DROP TABLE CardAndSTBNotRealTime');
        $this->addSql('DROP TABLE CardAndSTBRealTime');
        $this->addSql('DROP TABLE CardBlackList');
        $this->addSql('DROP TABLE CardFieldRestrict');
        $this->addSql('DROP TABLE ConditionNotRealTime');
        $this->addSql('DROP TABLE ConditionRealTime');
        $this->addSql('DROP TABLE EmmSI');
        $this->addSql('DROP TABLE EventRecordInfo');
        $this->addSql('DROP TABLE GOSCASVersion');
        $this->addSql('DROP TABLE GaoAnECMGFPRInfo');
        $this->addSql('DROP TABLE GaoAnURIInfo');
        $this->addSql('DROP TABLE OTAInfo');
        $this->addSql('DROP TABLE OldAccredit');
        $this->addSql('DROP TABLE OldAccreditPkg');
        $this->addSql('DROP TABLE PackageAndCardCorrespond');
        $this->addSql('DROP TABLE PackageAndCardLog');
        $this->addSql('DROP TABLE PackageAndProductCorrespond');
        $this->addSql('DROP TABLE PackageAndServiceAuthorize');
        $this->addSql('DROP TABLE PackageAndServiceCorrespond');
        $this->addSql('DROP TABLE PackageInfo');
        $this->addSql('DROP TABLE ProductInfo');
        $this->addSql('DROP TABLE RedoUpdatePkgLog');
        $this->addSql('DROP TABLE SMSAuthInfo');
        $this->addSql('DROP TABLE SMSVendorInfo');
        $this->addSql('DROP TABLE STBAndCardPairCorrespond');
        $this->addSql('DROP TABLE STBBlackList');
        $this->addSql('DROP TABLE SendEMM');
        $this->addSql('DROP TABLE ServiceInfo');
        $this->addSql('DROP TABLE TerminalInfo');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ACInfo (ACInfoID INT UNSIGNED AUTO_INCREMENT NOT NULL, ACIndex VARCHAR(16) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, ACData VARCHAR(2048) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, BeginTime CHAR(20) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, EndTime CHAR(20) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, ACVersion TINYINT(1) NOT NULL, Reserved1 BIGINT UNSIGNED DEFAULT NULL, Reserved2 BIGINT UNSIGNED DEFAULT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_ACIndex (ACIndex), INDEX IX_AreaID (AreaID), PRIMARY KEY(ACInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE Accredit (AccreditID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT NOT NULL, CurNext TINYINT(1) NOT NULL, ProductNumber BINARY(128) NOT NULL, Reserved TINYINT(1) NOT NULL, Resered0 VARCHAR(12) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, ProductStartTime DATETIME NOT NULL, ProductEndTime DATETIME NOT NULL, InsertTime DATETIME NOT NULL, ProductBank INT NOT NULL, INDEX IX_CardID (CardID), INDEX IX_ProductEndTime (ProductEndTime), INDEX IX_ProductStartTime (ProductStartTime), PRIMARY KEY(AccreditID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE AllCardStatus (AllCardStatusID INT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT NOT NULL, IsSend TINYINT(1) NOT NULL, CardStatus TINYINT(1) NOT NULL, SMSID BIGINT NOT NULL, SetCmdTime DATETIME NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_CardID (CardID), PRIMARY KEY(AllCardStatusID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE AllSendCard (AllSendCardID INT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT UNSIGNED NOT NULL, IsSend TINYINT(1) NOT NULL, MotherCardID BIGINT UNSIGNED NOT NULL, StandardFlag TINYINT(1) NOT NULL, DecryptCWTimes BIGINT UNSIGNED NOT NULL, IntervalTime BIGINT UNSIGNED NOT NULL, DealerArea INT NOT NULL, UserClass INT NOT NULL, UserArea BIGINT UNSIGNED NOT NULL, Name VARCHAR(40) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, Other VARCHAR(40) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, SMSID BIGINT UNSIGNED NOT NULL, INDEX IX_CardID (CardID), INDEX IX_SMSID (SMSID), PRIMARY KEY(AllSendCardID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE AllTableCount (AllTableCountID INT UNSIGNED AUTO_INCREMENT NOT NULL, TableName VARCHAR(32) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, DayNum INT DEFAULT NULL, DayCount BIGINT NOT NULL, PRIMARY KEY(AllTableCountID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE CardAndSTBNotRealTime (CardAndSTBNotRealTimeID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, TagID INT NOT NULL, EncryptType TINYINT(1) NOT NULL, CardOrSTBID BIGINT NOT NULL, CommandType INT NOT NULL, StartOrStopFlag TINYINT(1) NOT NULL, ContentLen INT NOT NULL, Content VARCHAR(4096) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, ExpiredTime DATETIME NOT NULL, INDEX index_CommandType (CommandType), INDEX IX_CardOrSTBID (CardOrSTBID), PRIMARY KEY(CardAndSTBNotRealTimeID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE CardAndSTBRealTime (CardAndSTBRealTimeID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, TagID INT NOT NULL, EncryptType TINYINT(1) NOT NULL, CardOrSTBID BIGINT NOT NULL, CommandType INT NOT NULL, ContentLen INT NOT NULL, Content VARCHAR(4096) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, ExpiredTime DATETIME NOT NULL, INDEX index_CommandType (CommandType), INDEX IX_CardOrSTBID (CardOrSTBID), PRIMARY KEY(CardAndSTBRealTimeID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE CardBlackList (CardBlackListID INT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT UNSIGNED NOT NULL, SetCmdTime DATETIME NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_CardID (CardID), INDEX IX_SetCmdTime (SetCmdTime), PRIMARY KEY(CardBlackListID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE CardFieldRestrict (CardFieldRestrictID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, ActionFlag TINYINT(1) NOT NULL, ConditionNum INT NOT NULL, CardField VARCHAR(512) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, Reserved BIGINT NOT NULL, SetCmdTime DATETIME NOT NULL, Reserved1 VARCHAR(2048) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, INDEX IX_SetCmdTime (SetCmdTime), PRIMARY KEY(CardFieldRestrictID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ConditionNotRealTime (ConditionNotRealTimeID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `Condition` VARCHAR(2048) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, EncryptType TINYINT(1) NOT NULL, CommandType INT NOT NULL, StartOrStopFlag TINYINT(1) NOT NULL, ContentLen INT NOT NULL, Content VARCHAR(4096) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, ExpiredTime DATETIME NOT NULL, INDEX index_CommandType (CommandType), PRIMARY KEY(ConditionNotRealTimeID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ConditionRealTime (ConditionRealTimeID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `Condition` VARCHAR(2048) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, EncryptType TINYINT(1) NOT NULL, CommandType INT NOT NULL, ContentLen INT NOT NULL, Content VARCHAR(4096) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, ExpiredTime DATETIME NOT NULL, EnCodeType INT UNSIGNED DEFAULT NULL, INDEX index_CommandType (CommandType), PRIMARY KEY(ConditionRealTimeID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE EmmSI (id INT AUTO_INCREMENT NOT NULL, si_table_id TINYINT(1) NOT NULL, si_table_data MEDIUMTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_bin`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE EventRecordInfo (TaskID INT UNSIGNED AUTO_INCREMENT NOT NULL, TaskName VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, Status TINYINT(1) NOT NULL, StartTime DATETIME NOT NULL, RunFrequence INT NOT NULL, Description VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, FilePath VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, UNIQUE INDEX UQ_TaskID (TaskID), UNIQUE INDEX UQ_TaskName (TaskName), PRIMARY KEY(TaskID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE GOSCASVersion (GOSCASVersionID TINYINT(1) NOT NULL, Version INT NOT NULL, PRIMARY KEY(GOSCASVersionID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE GaoAnECMGFPRInfo (GaoAnECMGFPRInfoID INT UNSIGNED AUTO_INCREMENT NOT NULL, `Index` VARCHAR(16) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, Data VARCHAR(2048) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, INDEX IX_Index (`Index`), PRIMARY KEY(GaoAnECMGFPRInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE GaoAnURIInfo (GaoAnURIInfoID INT UNSIGNED AUTO_INCREMENT NOT NULL, `Index` VARCHAR(16) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, Data VARCHAR(2048) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, SetCmdTime DATETIME NOT NULL, INDEX IX_Index (`Index`), PRIMARY KEY(GaoAnURIInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE OTAInfo (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, area_id INT UNSIGNED NOT NULL, ota_type INT UNSIGNED NOT NULL, cond TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, manufacturer_id INT UNSIGNED NOT NULL, stb_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, version_compare_mode INT UNSIGNED NOT NULL, original_version INT UNSIGNED NOT NULL, target_version INT UNSIGNED NOT NULL, ts_id INT UNSIGNED NOT NULL, frequency INT UNSIGNED NOT NULL, modulation INT UNSIGNED NOT NULL, symbol_rate INT UNSIGNED NOT NULL, ts_pid INT UNSIGNED NOT NULL, scrambler_ip VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, scrambler_port INT UNSIGNED NOT NULL, code_rate DOUBLE PRECISION NOT NULL, ts_path TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, INDEX area_index (area_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE OldAccredit (OldAccreditID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT NOT NULL, TapingCtrl TINYINT(1) NOT NULL, ProductNumber INT NOT NULL, ProductStartTime DATETIME NOT NULL, ProductEndTime DATETIME NOT NULL, SendTime DATETIME NOT NULL, INDEX IX_CardID (CardID), UNIQUE INDEX IX_Key (CardID, ProductNumber, ProductEndTime), INDEX IX_ProductEndTime (ProductEndTime), INDEX IX_ProductNumber (ProductNumber), INDEX IX_ProductStartTime (ProductStartTime), PRIMARY KEY(OldAccreditID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE OldAccreditPkg (OldAccreditPkgID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT NOT NULL, PkgId INT NOT NULL, TapingCtrl TINYINT(1) NOT NULL, ProductNumber INT NOT NULL, ProductStartTime DATETIME NOT NULL, ProductEndTime DATETIME NOT NULL, SendTime DATETIME NOT NULL, ProductStartTimeBak DATETIME NOT NULL, INDEX IX_CardID (CardID), INDEX IX_PkgId (PkgId), INDEX IX_ProductEndTime (ProductEndTime), INDEX IX_ProductNumber (ProductNumber), UNIQUE INDEX `Key` (CardID, ProductNumber, PkgId, ProductEndTime), PRIMARY KEY(OldAccreditPkgID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE PackageAndCardCorrespond (PackageAndCardCorrespondID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT NOT NULL, PackageNum INT NOT NULL, TapingCtrl TINYINT(1) NOT NULL, PackageStartTime DATETIME NOT NULL, PackageEndTime DATETIME NOT NULL, SendTime DATETIME NOT NULL, INDEX IX_CardID (CardID), INDEX IX_PackageEndTime (PackageEndTime), INDEX IX_PackageNum (PackageNum), INDEX IX_PackageStartTime (PackageStartTime), PRIMARY KEY(PackageAndCardCorrespondID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE PackageAndCardLog (PackageAndCardLogID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CardID BIGINT NOT NULL, PackageNum INT NOT NULL, TapingCtrl TINYINT(1) NOT NULL, QuickSendFlag TINYINT(1) NOT NULL, SendOrNot TINYINT(1) NOT NULL, PackageStartTime DATETIME NOT NULL, PackageEndTime DATETIME NOT NULL, SendTime DATETIME NOT NULL, MsgSource VARCHAR(200) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, SMSID BIGINT NOT NULL, STBID BIGINT NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, Reserved INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_CardID (CardID), INDEX IX_PackageEndTime (PackageEndTime), INDEX IX_PackageNum (PackageNum), INDEX IX_PackageStartTime (PackageStartTime), INDEX IX_Reserved (Reserved), PRIMARY KEY(PackageAndCardLogID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE PackageAndProductCorrespond (PackageAndProductCorrespondID INT UNSIGNED AUTO_INCREMENT NOT NULL, ProductNum INT NOT NULL, PackageNum INT NOT NULL, Reserved BIGINT NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_PackageNum (PackageNum), INDEX IX_ProductNum (ProductNum), PRIMARY KEY(PackageAndProductCorrespondID)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE PackageAndServiceAuthorize (PackageAndServiceAuthorizeID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, TerminateID BIGINT NOT NULL, AuthorizeType TINYINT(1) NOT NULL, PackageOrServiceID INT NOT NULL, AuthorizeStartTime DATETIME NOT NULL, AuthorizeEndTime DATETIME NOT NULL, Reserved1 BIGINT NOT NULL, Reserved2 BIGINT NOT NULL, SendTime DATETIME NOT NULL, INDEX IX_AuthorizeEndTime (AuthorizeEndTime), INDEX IX_AuthorizeStartTime (AuthorizeStartTime), INDEX IX_PackageOrServiceID (PackageOrServiceID), INDEX IX_TerminateID (TerminateID), PRIMARY KEY(PackageAndServiceAuthorizeID)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE PackageAndServiceCorrespond (PackageAndServiceCorrespondID INT UNSIGNED AUTO_INCREMENT NOT NULL, ServiceID INT NOT NULL, PackageID INT NOT NULL, Reserved BIGINT NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_PackageID (PackageID), INDEX IX_ServiceID (ServiceID), PRIMARY KEY(PackageAndServiceCorrespondID)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE PackageInfo (PackageInfoID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PackageNum INT NOT NULL, Description VARCHAR(1024) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, Reserved1 BIGINT NOT NULL, Reserved2 BIGINT NOT NULL, SMSID BIGINT NOT NULL, SetCmdTime DATETIME NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_PackageNum (PackageNum), INDEX IX_SetCmdTime (SetCmdTime), PRIMARY KEY(PackageInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ProductInfo (ProductInfoID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, ProductNum INT NOT NULL, Description VARCHAR(1024) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, Reserved1 BIGINT NOT NULL, Reserved2 BIGINT NOT NULL, SMSID BIGINT NOT NULL, SetCmdTime DATETIME NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_ProductNum (ProductNum), INDEX IX_SetCmdTime (SetCmdTime), PRIMARY KEY(ProductInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE RedoUpdatePkgLog (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PackageId INT NOT NULL, IsAdd INT NOT NULL, ProductNumber INT NOT NULL, InsertTime DATETIME DEFAULT NULL, UNIQUE INDEX INDEX_ID (id), INDEX INDEX_PkgId (PackageId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE SMSAuthInfo (SMSAuthInfoID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, SMSID BIGINT UNSIGNED NOT NULL, SMSIP VARCHAR(16) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, SMSMAC VARCHAR(32) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, SMSDescription VARCHAR(200) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, ConnStatus TINYINT(1) DEFAULT NULL, EMMGCtrl TINYINT(1) DEFAULT NULL, AreaID INT UNSIGNED DEFAULT NULL, AreaName VARCHAR(20) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, AreaCtrl TINYINT(1) DEFAULT NULL, INDEX IX_SMSID (SMSID), PRIMARY KEY(SMSAuthInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE SMSVendorInfo (SMSVendorInfoID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, SMSVendorID INT NOT NULL, SMSVendorInfo VARCHAR(1000) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, SMSVendorPassWD VARCHAR(8000) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, HostName VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY(SMSVendorInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE STBAndCardPairCorrespond (STBAndCardPairCorrespondID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, STBID BIGINT NOT NULL, STBReserved INT NOT NULL, CardID BIGINT NOT NULL, CardReserved INT NOT NULL, SetCmdTime DATETIME NOT NULL, INDEX index_CardID (CardID), INDEX index_STBID (STBID), PRIMARY KEY(STBAndCardPairCorrespondID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE STBBlackList (STBBlackListID INT UNSIGNED AUTO_INCREMENT NOT NULL, STBID BIGINT UNSIGNED NOT NULL, SetCmdTime DATETIME NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_STBID (STBID), PRIMARY KEY(STBBlackListID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE SendEMM (SendEMMID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, ExpiredTime DATETIME NOT NULL, EMMData VARCHAR(2000) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, INDEX IX_ExpiredTime (ExpiredTime), PRIMARY KEY(SendEMMID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ServiceInfo (ServiceInfoID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, ServiceID INT UNSIGNED NOT NULL, ServiceName VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, Reserved1 BIGINT NOT NULL, Reserved2 BIGINT NOT NULL, SMSID BIGINT UNSIGNED NOT NULL, SetCmdTime DATETIME NOT NULL, AreaID INT UNSIGNED DEFAULT NULL, INDEX IX_AreaID (AreaID), INDEX IX_ServiceID (ServiceID), PRIMARY KEY(ServiceInfoID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE TerminalInfo (TerminalID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, ChipID BIGINT NOT NULL, ActvFun VARCHAR(1024) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, ActvDate DATETIME NOT NULL, ExprDate DATETIME NOT NULL, SendTime DATETIME NOT NULL, NetworkID BIGINT NOT NULL, OperatorID BIGINT NOT NULL, DeviceType INT NOT NULL, OperateName VARCHAR(1024) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY(TerminalID)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE activation DROP FOREIGN KEY FK_1C6860774ACC9A20');
        $this->addSql('ALTER TABLE activation DROP FOREIGN KEY FK_1C686077B03A8386');
        $this->addSql('ALTER TABLE card_customer DROP FOREIGN KEY FK_3808408A9395C3F3');
        $this->addSql('ALTER TABLE card_customer DROP FOREIGN KEY FK_3808408A4ACC9A20');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E09F2C56620');
        $this->addSql('ALTER TABLE souscription DROP FOREIGN KEY FK_2AED620D6C8DF983');
        $this->addSql('ALTER TABLE souscription DROP FOREIGN KEY FK_2AED620D9395C3F3');
        $this->addSql('DROP TABLE activation');
        $this->addSql('DROP TABLE bouquet');
        $this->addSql('DROP TABLE card');
        $this->addSql('DROP TABLE card_customer');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE souscription');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
